server:
  port: ${PORT:8863}
eureka:
  client:
   # fetch-registry: false
    register-with-eureka: true
    serviceurl:
      defaultZone: http://localhost:8850/eureka/
message: Configuracion de Cajero en el servidor levantado!
spring:
  application:
    name: ms_cajero
