server:
  port: ${PORT:8864}
message: Configuracion de producto en el servidor levantado!
spring:
 datosource:
   driver-class-name: com.msql.cj.jdbc.Driver
   password: 12345678
   url: jdbc:msql://localhost:3306/crudcloud?serverTimezone=UTC
   username: root
  jpa:
   hibernate:
     ddl-auto: update
     database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    config:
       uri: http://localhost:8860
